cmd/principal: Make error message slightly more helpful.
Assuming /tmp/foo doesn't exist, prior to this change:

  $ V23_CREDENTIALS=/tmp/foo principal seekblessings
  ERROR: principal: /tmp/foo is not a directory
  $ mkdir /tmp/foo
  $ V23_CREDENTIALS=/tmp/foo principal seekblessings
  ERROR: principal: couldn't find a suitable agent binary (failed to find v23agentd: exec: "v23agentd": executable file not found in $PATH) or load principal in the address space of the current process (open /tmp/foo/privatekey.pem: no such file or directory)

With this change:

  $ V23_CREDENTIALS=/tmp/foo principal seekblessings
  ERROR: failed to initialize credentials, perhaps you need to create them with 'principal create /tmp/foo' (error: principal: /tmp/foo is not a directory)
  $ mkdir /tmp/foo
  $ V23_CREDENTIALS=/tmp/foo principal seekblessings
  ERROR: failed to initialize credentials, perhaps you need to create them with 'principal create /tmp/foo' (error: principal: couldn't load credentials (open /tmp/foo/privatekey.pem: no such file or directory) or start an agent (failed to find v23agentd: exec: "v23agentd": executable file not found in $PATH))

Change-Id: I751f3c43d860afc6fdca543494d0bca75b0494e7