runtime/internal/naming/namespace: detect if resolved name starts with endpoint
A common and frustrating experience is for users to pass in
<endpoint>/suffix (or host:port/suffix) to an RPC client.  Our system
attempts to resolve <endpoint> as a name component, and the resulting
error is confusing to the user.
See: https://github.com/vanadium/issues/issues/1290

This CL makes namespace.Resolve detect if that may be the case, and
report back to the user by means of a sub-error.
The change in rpc/client.go ensures that the error returned by Resolve
makes it back to the user.

Sample output:

BEFORE CL:
$ vrpc signature @6@...@@/foo
ERROR: Signature failed:
vrpc:<rpc.Client>"@6@@...@@/foo".__Signature:
No usable servers found

AFTER CL:
$ vrpc signature @6@...@@/foo
ERROR: Signature failed: vrpc:<rpc.Client>"@6@@..@@/foo".__Signature: No usable servers found: @6@@...@@/foo mounttabled "@6@@...@@/foo".ResolveStep Name @6@@...@@/foo doesn't exist [Did you mean: /@6@@...@@/foo]

Change-Id: I8662101eed4b232357b850ff6ea2a5c38292d1bd