services/security/agent: Use lockfile to manage sockets used by the keymanager service.
Without this change, when the agent died and restarted it would be
unable to serve principals for other processes via the keymgr service
because the old socket would be left around and the ipc.Listen call
would fail with:

ERROR: Run failed:
deviced:"apps/VLabProxy/20150810-20:12:31.5634/20150810-20:12:32.9841".Run:
operation failed: ServePrincipal failed: v.io/v23/verror.Unknown:
listen unix /var/veyron/dm/dmroot/socks/rnd_sock_dir_vlabproxy/s: bind:
address already in use,

(this message is from the device manager trying to restart an
application)

We had anticipated this problem for agentd and were using lockfile in
agentd/main.go. Use the same technique for other keys that may be served
by the agent.

Change-Id: Icecd545991a1b24dda6257c1f0cc8e80ed03ec55