ref: Add cmdline.HideGlobalFlagsExcept() to clean up help.
Closes: veyron/release-issue#1905

---------- Example of new output ----------
$ vrpc
ERROR: vrpc: no command specified

Command vrpc sends and receives Vanadium remote procedure calls.

Usage:
vrpc <command>

The vrpc commands are:
signature   Describe the interfaces of a Vanadium server
call        Call a method of a Vanadium server
identify    Reveal blessings presented by a Vanadium server
help        Display help for commands or topics
Run "vrpc help [command]" for command usage.

Run "vrpc help -style=full" to show all global flags.
----------

This CL shortens the default cmdline usage output, so that you
have a chance at seeing the important parts before it scrolls off
the screen.  The main culprit for long output is our long list of
global flags.

By default, nothing has changed; all global flags are shown in
usage.  Calling cmdline.HideGlobalFlagsExcept() causes the
default behavior to hide global flags, except for the given
regexps.  This mechanism was chosen since it seems better to have
global flags shown if the developer doesn't do anything special,
but if they call the method it's easier to specify a whitelist
than a blacklist.

To show all global flags you use "help -style=full", or set the
envvar CMDLINE_STYLE=full for root commands with no subcommands.
When any global flags are hidden, the usage includes a line
desribing the exact command to run to get the full output.

The -style=godoc output always shows all global flags.

MultiPart: 3/3

Change-Id: Ib397adf220489b251bd0b03badd0199c24c7d4a0